#!/usr/bin/env bun
/**
 * build-publish.mjs — compile this integration into a SHAREABLE server.ts.
 *
 * VoiceOS's Share button ships only five files (server.ts, widgetKit.ts,
 * package.json, the manifest, the icon) and does NOT trace imports — so a
 * server.ts that imports "./client.ts", "./cards.ts", … arrives broken, and one
 * that imports npm packages needs the network on first run. This inlines every
 * local module AND every npm dependency into a single self-contained server.ts
 * (only node: builtins stay external, and those are always present). `node
 * server.ts` type-strips it and bun runs it directly — the exact two runtimes
 * the recipient's regenerated run.sh resolves.
 *
 * The hand-written source is kept as server.src.ts. The FIRST run snapshots the
 * current server.ts into server.src.ts, then every run builds server.src.ts →
 * server.ts. After this, edit server.src.ts (never the bundled server.ts) and
 * re-run.
 *
 *     bun run build-publish        # from the integration folder
 */
import { existsSync, copyFileSync, statSync, readFileSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";

const dir = join(dirname(fileURLToPath(import.meta.url)), ".."); // integration root
const src = join(dir, "server.src.ts");
const out = join(dir, "server.ts");

// First run: preserve the hand-written server.ts as server.src.ts. Idempotent —
// once server.src.ts exists it is the source of truth and is never overwritten
// by the (now-bundled) server.ts.
if (!existsSync(src)) {
  if (!existsSync(out)) {
    console.error("build-publish: no server.ts to compile."); process.exit(1);
  }
  copyFileSync(out, src);
  console.error("build-publish: snapshotted server.ts → server.src.ts (edit server.src.ts from now on)");
}

// Freeze every runtime-read card asset (widget HTML, adapters, CSS, mark, rfb)
// into assets.generated.ts FIRST, so the bundle below inlines them. Without this
// a shared build boots straight into `ENOENT widgets/connect.html` — the
// widgets/ folder never ships with the five files VoiceOS's Share button sends.
const gen = spawnSync("node", ["scripts/inline-assets.mjs"], { cwd: dir, stdio: "inherit" });
if (gen.status !== 0) { console.error("build-publish: inline-assets failed."); process.exit(gen.status ?? 1); }

// Keep the cached manifest and bundled SDK helpers in sync with source.
const manifest = spawnSync("bun", ["run", "build-intents"], { cwd: dir, stdio: "inherit" });
if (manifest.status !== 0) process.exit(manifest.status ?? 1);

const r = spawnSync(
  "bun",
  ["build", "--target=node", "server.src.ts", "--outfile", "server.ts"],
  { cwd: dir, stdio: "inherit" },
);
if (r.status !== 0) { console.error("build-publish: bun build failed."); process.exit(r.status ?? 1); }

// The share format caps the entire expanded package at 2 MiB. Compress the
// self-contained ESM bundle and inflate it in memory (no source or credentials
// written to disk). Node's createRequire needs the launcher's file URL rather
// than the data: module URL; all other imports are node: builtins.
const compressed = gzipSync(readFileSync(out), { level: 9 }).toString("base64");
writeFileSync(out, `// Generated by bun run build-publish; edit server.src.ts instead.\n` +
  `import { gunzipSync } from "node:zlib";\n` +
  `const source = gunzipSync(Buffer.from(${JSON.stringify(compressed)}, "base64")).toString("utf8")\n` +
  `  .replaceAll("import.meta.url", JSON.stringify(import.meta.url));\n` +
  `const moduleUrl = typeof Bun !== "undefined" ? URL.createObjectURL(new Blob([source], { type: "text/javascript" }))\n` +
  `  : "data:text/javascript;base64," + Buffer.from(source).toString("base64");\n` +
  `try { await import(moduleUrl); } finally { if (moduleUrl.startsWith("blob:")) URL.revokeObjectURL(moduleUrl); }\n`);
const shareFiles = ["server.ts", "widgetKit.ts", "package.json", "voiceos.integration.json", "icon.png"];
const total = shareFiles.reduce((bytes, file) => bytes + statSync(join(dir, file)).size, 0);
if (total > 2 * 1024 * 1024) throw new Error(`Share package exceeds 2 MiB: ${total} bytes`);
console.error(`build-publish: total share payload ${total} bytes (under 2 MiB)`);

const bytes = statSync(out).size;
console.error(`build-publish: wrote self-contained server.ts (${(bytes / 1024 / 1024).toFixed(2)} MB). Run \`node ../../scripts/recipient-sim.mjs <app>\` to verify.`);
