#!/usr/bin/env node
/**
 * inline-assets.mjs — freeze every runtime-read asset into a TS module.
 *
 * cards.ts renders the notch cards from files on disk (widgets/*.html, the two
 * adapters, the messaging CSS, mark.png, rfb.b64). VoiceOS's Share button ships
 * only server.ts + widgetKit.ts + package.json + manifest + icon — the widgets/
 * folder and mark.png never travel, so a shared build crashes on boot with
 * `ENOENT widgets/connect.html` before it can serve a single tool.
 *
 * This writes assets.generated.ts with each asset as a plain string constant, so
 * `bun build` inlines them into the self-contained server.ts. Runtime-agnostic:
 * pure string literals work identically under bun and node/tsx. The ONLY asset
 * that stays a runtime read is the Grok gateway descriptor (client.ts) — that is
 * the user's live session and must be read on their machine, not baked in.
 *
 *     node scripts/inline-assets.mjs      # from the integration folder
 *
 * build-publish.mjs runs this automatically before bundling.
 */
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const text = (rel) => readFileSync(join(root, rel), "utf8");
const s = (v) => JSON.stringify(v); // safe for any HTML/JS/CSS content

const NAMES = ["connect", "show", "sent-group", "sent", "create", "thread", "screen", "computer"];
const widgets = Object.fromEntries(NAMES.map((n) => [n, text(`widgets/${n}.html`)]));
const markB64 = readFileSync(join(root, "mark.png")).toString("base64");

function computerViewerBinary() {
  const scratch = mkdtempSync(join(tmpdir(), "grokbot-viewer-build-"));
  const source = join(root, "native", "ComputerViewer.swift");
  const arm64 = join(scratch, "ComputerViewer-arm64");
  const x64 = join(scratch, "ComputerViewer-x86_64");
  const universal = join(scratch, "ComputerViewer");
  const run = (command, args) => {
    const result = spawnSync(command, args, { encoding: "utf8" });
    if (result.status !== 0) {
      const detail = String(result.stderr || result.stdout || "native build failed").trim();
      throw new Error(`computer viewer build failed: ${detail}`);
    }
  };
  try {
    const common = ["-O", "-parse-as-library", source, "-framework", "AppKit", "-framework", "WebKit"];
    run("/usr/bin/swiftc", ["-target", "arm64-apple-macos13.0", ...common, "-o", arm64]);
    run("/usr/bin/swiftc", ["-target", "x86_64-apple-macos13.0", ...common, "-o", x64]);
    run("/usr/bin/lipo", ["-create", arm64, x64, "-output", universal]);
    run("/usr/bin/codesign", ["--force", "--sign", "-", universal]);
    return readFileSync(universal).toString("base64");
  } finally {
    rmSync(scratch, { recursive: true, force: true });
  }
}

const computerViewerB64 = computerViewerBinary();

const out = `// AUTO-GENERATED by scripts/inline-assets.mjs — DO NOT EDIT BY HAND.
// Regenerate with: node scripts/inline-assets.mjs (build-publish runs it for you).
// Embeds every runtime-read card asset so the shared single-file server.ts is
// self-contained — no widgets/ folder or mark.png needs to ship alongside it.
export const WIDGETS: Record<string, string> = ${s(widgets)};
export const MESSAGING_ADAPTER = ${s(text("widgets/messaging-adapter.js"))};
export const CONFIRMATION_ADAPTER = ${s(text("widgets/confirmation-adapter.js"))};
export const MESSAGING_CSS = ${s(text("widgets/messaging-adapter.css"))};
export const MARK_DATA_URI = ${s(`data:image/png;base64,${markB64}`)};
export const RFB_B64 = ${s(text("widgets/rfb.b64").trim())};
export const RFB_FULL_B64 = ${s(text("widgets/rfb-full.b64").trim())};
export const COMPUTER_VIEWER_BINARY_B64 = ${s(computerViewerB64)};
`;

writeFileSync(join(root, "assets.generated.ts"), out);
console.error(`inline-assets: wrote assets.generated.ts (${(out.length / 1024).toFixed(1)} KB, ${NAMES.length} widgets + adapters + mark + rfb + native viewer)`);
