#!/usr/bin/env node
/**
 * inline-assets.mjs — freeze every runtime-read asset into a TS module.
 *
 * cards.ts renders the notch cards from files on disk (widgets/*.html, the two
 * adapters, the messaging CSS, mark.png, rfb.b64). VoiceOS's Share button ships
 * only server.ts + widgetKit.ts + package.json + manifest + icon — the widgets/
 * folder and mark.png never travel, so a shared build crashes on boot with
 * `ENOENT widgets/connect.html` before it can serve a single tool.
 *
 * This writes assets.generated.ts with each asset as a plain string constant, so
 * `bun build` inlines them into the self-contained server.ts. Runtime-agnostic:
 * pure string literals work identically under bun and node/tsx. The ONLY asset
 * that stays a runtime read is the Grok gateway descriptor (client.ts) — that is
 * the user's live session and must be read on their machine, not baked in.
 *
 *     node scripts/inline-assets.mjs      # from the integration folder
 *
 * build-publish.mjs runs this automatically before bundling.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const text = (rel) => readFileSync(join(root, rel), "utf8");
const s = (v) => JSON.stringify(v); // safe for any HTML/JS/CSS content

const NAMES = ["connect", "show", "sent-group", "sent", "create", "thread", "screen"];
const widgets = Object.fromEntries(NAMES.map((n) => [n, text(`widgets/${n}.html`)]));
const markB64 = readFileSync(join(root, "mark.png")).toString("base64");

const out = `// AUTO-GENERATED by scripts/inline-assets.mjs — DO NOT EDIT BY HAND.
// Regenerate with: node scripts/inline-assets.mjs (build-publish runs it for you).
// Embeds every runtime-read card asset so the shared single-file server.ts is
// self-contained — no widgets/ folder or mark.png needs to ship alongside it.
export const WIDGETS: Record<string, string> = ${s(widgets)};
export const MESSAGING_ADAPTER = ${s(text("widgets/messaging-adapter.js"))};
export const CONFIRMATION_ADAPTER = ${s(text("widgets/confirmation-adapter.js"))};
export const MESSAGING_CSS = ${s(text("widgets/messaging-adapter.css"))};
export const MARK_DATA_URI = ${s(`data:image/png;base64,${markB64}`)};
export const RFB_B64 = ${s(text("widgets/rfb.b64").trim())};
`;

writeFileSync(join(root, "assets.generated.ts"), out);
console.error(`inline-assets: wrote assets.generated.ts (${(out.length / 1024).toFixed(1)} KB, ${NAMES.length} widgets + adapters + mark + rfb)`);
