#!/usr/bin/env node
/**
 * inline-assets.mjs — freeze every runtime-read asset into a TS module.
 *
 * cards.ts renders the notch cards from files on disk (widgets/*.html, the
 * adapters, the messaging CSS, the live chat + composer scripts and styles, the
 * markdown CSS, mark.png, rfb.b64). VoiceOS's Share button ships
 * only server.ts + widgetKit.ts + package.json + manifest + icon — the widgets/
 * folder and mark.png never travel, so a shared build crashes on boot with
 * `ENOENT widgets/connect.html` before it can serve a single tool.
 *
 * This writes assets.generated.ts with each asset as a plain string constant, so
 * `bun build` inlines them into the self-contained server.ts. Runtime-agnostic:
 * pure string literals work identically under bun and node/tsx. The ONLY asset
 * that stays a runtime read is the Grok gateway descriptor (client.ts) — that is
 * the user's live session and must be read on their machine, not baked in.
 *
 *     node scripts/inline-assets.mjs      # from the integration folder
 *
 * build-publish.mjs runs this automatically before bundling.
 */
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { transformSync } from "esbuild";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const text = (rel) => readFileSync(join(root, rel), "utf8");
const s = (v) => JSON.stringify(v); // safe for any HTML/JS/CSS content
// The scripts and styles injected into the thread and show cards share the
// glance cap (cards.ts MAX_GLANCE_CHARS) with the handoff itself, and every byte they spend is a
// message the card cannot show. Whitespace and comments only (esbuild is a
// pinned devDependency, so the frozen bytes move only with the lockfile):
// names, globals (LiveChat, ComposerKit) and behavior are unchanged.
// The widget HTML is the design handoff and stays verbatim.
const minified = (rel) => transformSync(text(rel), {
  loader: rel.endsWith(".css") ? "css" : "js", minifyWhitespace: true, charset: "utf8", legalComments: "none",
}).code.trim();

const NAMES = ["connect", "show", "create", "screen", "computer"];
const widgets = Object.fromEntries(NAMES.map((n) => [n, text(`widgets/${n}.html`)]));
// The mark draws at 16px, so a 32px copy covers a 2x display; the 64px source
// would spend ~3KB more of every card's glance budget on pixels no screen draws.
function markPng() {
  const scratch = mkdtempSync(join(tmpdir(), "grokbot-mark-"));
  try {
    const out = join(scratch, "mark.png");
    const result = spawnSync("/usr/bin/sips", ["-Z", "32", join(root, "mark.png"), "--out", out], { encoding: "utf8" });
    if (result.status !== 0) throw new Error(`mark resize failed: ${String(result.stderr || result.stdout).trim()}`);
    return readFileSync(out);
  } finally {
    rmSync(scratch, { recursive: true, force: true });
  }
}
const markB64 = markPng().toString("base64");

function computerViewerBinary() {
  const scratch = mkdtempSync(join(tmpdir(), "grokbot-viewer-build-"));
  const source = join(root, "native", "ComputerViewer.swift");
  const arm64 = join(scratch, "ComputerViewer-arm64");
  const x64 = join(scratch, "ComputerViewer-x86_64");
  const universal = join(scratch, "ComputerViewer");
  const run = (command, args) => {
    const result = spawnSync(command, args, { encoding: "utf8" });
    if (result.status !== 0) {
      const detail = String(result.stderr || result.stdout || "native build failed").trim();
      throw new Error(`computer viewer build failed: ${detail}`);
    }
  };
  try {
    const common = ["-O", "-parse-as-library", source, "-framework", "AppKit", "-framework", "WebKit"];
    run("/usr/bin/swiftc", ["-target", "arm64-apple-macos13.0", ...common, "-o", arm64]);
    run("/usr/bin/swiftc", ["-target", "x86_64-apple-macos13.0", ...common, "-o", x64]);
    run("/usr/bin/lipo", ["-create", arm64, x64, "-output", universal]);
    run("/usr/bin/codesign", ["--force", "--sign", "-", universal]);
    return readFileSync(universal).toString("base64");
  } finally {
    rmSync(scratch, { recursive: true, force: true });
  }
}

const computerViewerB64 = computerViewerBinary();

const out = `// AUTO-GENERATED by scripts/inline-assets.mjs — DO NOT EDIT BY HAND.
// Regenerate with: node scripts/inline-assets.mjs (build-publish runs it for you).
// Embeds every runtime-read card asset so the shared single-file server.ts is
// self-contained — no widgets/ folder or mark.png needs to ship alongside it.
export const WIDGETS: Record<string, string> = ${s(widgets)};
export const LIVE_CHAT_JS = ${s(minified("widgets/live-chat.js"))};
export const LIVE_CHAT_CSS = ${s(minified("widgets/live-chat.css"))};
export const MARKDOWN_CSS = ${s(minified("widgets/markdown.css"))};
export const COMPOSER_KIT_JS = ${s(minified("widgets/composer-kit.js"))};
export const COMPOSER_KIT_CSS = ${s(minified("widgets/composer-kit.css"))};
export const SHOW_ADAPTER = ${s(minified("widgets/show-adapter.js"))};
export const SHOW_CSS = ${s(minified("widgets/show-adapter.css"))};
export const MARK_DATA_URI = ${s(`data:image/png;base64,${markB64}`)};
export const RFB_B64 = ${s(text("widgets/rfb.b64").trim())};
export const RFB_FULL_B64 = ${s(text("widgets/rfb-full.b64").trim())};
export const COMPUTER_VIEWER_BINARY_B64 = ${s(computerViewerB64)};
`;

writeFileSync(join(root, "assets.generated.ts"), out);
console.error(`inline-assets: wrote assets.generated.ts (${(out.length / 1024).toFixed(1)} KB, ${NAMES.length} widgets + adapters + live chat + composer + mark + rfb + native viewer)`);
